version: '2'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
       - "7000:7000"
    depends_on:
    - mongo
    env_file: .env
  mongo:
    image: mongo
    ports:
    - "27017:27017"